# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.17.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.17.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/camiloocampo/Documents/Max 8/Packages/min-devkit/source/projects/min.genetic"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/camiloocampo/Documents/Max 8/Packages/min-devkit/source/projects/min.genetic"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.17.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.17.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.17.1/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/camiloocampo/Documents/Max 8/Packages/min-devkit/source/projects/min.genetic/CMakeFiles" "/Users/camiloocampo/Documents/Max 8/Packages/min-devkit/source/projects/min.genetic/CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/camiloocampo/Documents/Max 8/Packages/min-devkit/source/projects/min.genetic/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named min.genetic_test

# Build rule for target.
min.genetic_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 min.genetic_test
.PHONY : min.genetic_test

# fast build rule for target.
min.genetic_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/build
.PHONY : min.genetic_test/fast

#=============================================================================
# Target rules for targets named min.genetic

# Build rule for target.
min.genetic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 min.genetic
.PHONY : min.genetic

# fast build rule for target.
min.genetic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/build
.PHONY : min.genetic/fast

dna.o: dna.cpp.o

.PHONY : dna.o

# target to build an object file
dna.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/dna.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/dna.cpp.o
.PHONY : dna.cpp.o

dna.i: dna.cpp.i

.PHONY : dna.i

# target to preprocess a source file
dna.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/dna.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/dna.cpp.i
.PHONY : dna.cpp.i

dna.s: dna.cpp.s

.PHONY : dna.s

# target to generate assembly for a file
dna.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/dna.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/dna.cpp.s
.PHONY : dna.cpp.s

min.genetic.o: min.genetic.cpp.o

.PHONY : min.genetic.o

# target to build an object file
min.genetic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/min.genetic.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/min.genetic.cpp.o
.PHONY : min.genetic.cpp.o

min.genetic.i: min.genetic.cpp.i

.PHONY : min.genetic.i

# target to preprocess a source file
min.genetic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/min.genetic.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/min.genetic.cpp.i
.PHONY : min.genetic.cpp.i

min.genetic.s: min.genetic.cpp.s

.PHONY : min.genetic.s

# target to generate assembly for a file
min.genetic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/min.genetic.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/min.genetic.cpp.s
.PHONY : min.genetic.cpp.s

min.genetic_test.o: min.genetic_test.cpp.o

.PHONY : min.genetic_test.o

# target to build an object file
min.genetic_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/min.genetic_test.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/min.genetic_test.cpp.o
.PHONY : min.genetic_test.cpp.o

min.genetic_test.i: min.genetic_test.cpp.i

.PHONY : min.genetic_test.i

# target to preprocess a source file
min.genetic_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/min.genetic_test.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/min.genetic_test.cpp.i
.PHONY : min.genetic_test.cpp.i

min.genetic_test.s: min.genetic_test.cpp.s

.PHONY : min.genetic_test.s

# target to generate assembly for a file
min.genetic_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/min.genetic_test.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/min.genetic_test.cpp.s
.PHONY : min.genetic_test.cpp.s

population.o: population.cpp.o

.PHONY : population.o

# target to build an object file
population.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/population.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/population.cpp.o
.PHONY : population.cpp.o

population.i: population.cpp.i

.PHONY : population.i

# target to preprocess a source file
population.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/population.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/population.cpp.i
.PHONY : population.cpp.i

population.s: population.cpp.s

.PHONY : population.s

# target to generate assembly for a file
population.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/population.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/population.cpp.s
.PHONY : population.cpp.s

workerthread.o: workerthread.cpp.o

.PHONY : workerthread.o

# target to build an object file
workerthread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/workerthread.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/workerthread.cpp.o
.PHONY : workerthread.cpp.o

workerthread.i: workerthread.cpp.i

.PHONY : workerthread.i

# target to preprocess a source file
workerthread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/workerthread.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/workerthread.cpp.i
.PHONY : workerthread.cpp.i

workerthread.s: workerthread.cpp.s

.PHONY : workerthread.s

# target to generate assembly for a file
workerthread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic_test.dir/build.make CMakeFiles/min.genetic_test.dir/workerthread.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/min.genetic.dir/build.make CMakeFiles/min.genetic.dir/workerthread.cpp.s
.PHONY : workerthread.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... min.genetic"
	@echo "... min.genetic_test"
	@echo "... dna.o"
	@echo "... dna.i"
	@echo "... dna.s"
	@echo "... min.genetic.o"
	@echo "... min.genetic.i"
	@echo "... min.genetic.s"
	@echo "... min.genetic_test.o"
	@echo "... min.genetic_test.i"
	@echo "... min.genetic_test.s"
	@echo "... population.o"
	@echo "... population.i"
	@echo "... population.s"
	@echo "... workerthread.o"
	@echo "... workerthread.i"
	@echo "... workerthread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

